platform :ios, '15.5'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
# Disable CocoaPods analytics by adding the following line.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Add your target to the file
target 'Runner' do
  use_frameworks!

  # Pods for Runner
  pod 'Flutter', :path => 'Flutter'
  pod 'google_mlkit_barcode_scanning'

end